import { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const translations = {
  en: {
    browse: 'Browse',
    browseTitle: 'Exercise Library',
    searchByName: 'Search by name (English or Vietnamese)',
    all: 'All',
    noResultsFound: 'No exercises found.',
    loadingMore: 'Loading more...',
    appTitle: 'AI Fitness Recommender',
    profile: 'Profile',
    inputPlaceholder: 'Describe your workout goal (e.g. build upper chest with dumbbell)',
    getSuggestions: 'Analyze & Recommend',
    loading: 'AI is analyzing...',
    recommendedFor: 'Target Focus',
    noExercisesFound: 'No exercises found matching your description.',
    enterLongerDescription: 'Please enter at least 3 characters',
    failedToConnect: 'Failed to connect to backend',
    instructions: 'Execution Instructions',
    secondaryMuscles: 'Secondary Muscles',
    noInstructions: 'No instructions available for this exercise.',
    saveToFavorites: 'Save to Favorites',
    saved: 'Saved',
    saving: 'Saving...',
    logWorkout: 'Log Workout (RPE & Sets)',
    sets: 'Sets',
    reps: 'Reps',
    weightKg: 'Weight (kg)',
    rpeScore: 'Perceived Exertion (RPE 1-10)',
    confirmLog: 'Confirm Log',
    workoutLogged: 'Workout logged successfully!',
    success: 'Success',
    error: 'Error',
    login: 'Log In',
    loggingIn: 'Logging in...',
    signUp: 'Sign Up',
    creatingAccount: 'Creating account...',
    email: 'Email',
    password: 'Password',
    passwordMin: 'Password (min 6 characters)',
    name: 'Name',
    noAccount: "Don't have an account? Register",
    haveAccount: 'Already have an account? Log In',
    createAccount: 'Create Account',
    passwordTooShort: 'Password must be at least 6 characters',
    favoriteExercises: '⭐ Favorite Exercises',
    workoutHistory: '📋 Workout History',
    logOut: 'Log Out',
    noFavorites: 'No favorite exercises yet.',
    remove: 'Remove',
    noWorkoutLogs: 'No workout logs yet.',
    language: 'Language',
    detail: 'Exercise Detail',
    favoritesTitle: 'Favorites',
    historyTitle: 'Workout History',
    profileTitle: 'Profile',
    adminDashboard: 'Admin Dashboard',
    adminExercises: 'Manage Exercises',
    totalUsers: 'Total Users',
    totalExercises: 'Total Exercises',
    totalFavorites: 'Total Favorites',
    totalWorkoutLogs: 'Total Workout Logs',
    mostFavorited: 'Most Favorited Exercises',
    addExercise: 'Add Exercise',
    editExercise: 'Edit Exercise',
    deleteExercise: 'Delete',
    confirmDelete: 'Are you sure you want to delete this exercise?',
    save: 'Save',
    cancel: 'Cancel',
    bodyPart: 'Body Part',
    equipment: 'Equipment',
    exerciseName: 'Exercise Name',
    aiAccuracy: 'AI Model Accuracy ~95%',
    aiEngineBadge: 'AI Adaptive Engine Active',
    aiConfidence: 'AI Confidence Score',
    confidenceHigh: 'High Precision',
    confidenceMedium: 'Moderate Match',
    confidenceLow: 'Low Precision',
    identifiedKeywords: 'Keywords Identified',
    alternativeSuggestions: 'Quick Switch Muscle Group',
    clarificationTip: 'Tip: Try adding specific equipment or muscle focus for higher precision.',
    quickPrompts: 'Quick Focus Prompts',
    match: 'Match',
    formGuidance: 'AI Form & Technique Guidance',
    formAccuracyTarget: 'Target Form Accuracy ≥ 85%',
    formTipChest: 'Keep shoulder blades retracted and core braced throughout the press.',
    formTipBack: 'Drive through your elbows and avoid excessive torso swinging.',
    formTipLegs: 'Ensure knees track in line with your toes and maintain a neutral spine.',
    formTipShoulders: 'Avoid flaring your elbows and control the eccentric lowering phase.',
    formTipDefault: 'Maintain controlled tempo, full range of motion, and steady breathing.',
    substitutionsTitle: 'Alternative Exercises (Same Muscle Target)',
    noSubstitutions: 'No alternative exercises found.',
    // Onboarding & Profile Keys (FR-002, FR-004, FR-005 SRS)
    onboardingTitle: 'Set Up Your Fitness Profile',
    onboardingSubtitle: 'Let AI personalize the optimal workout routine for your body.',
    step1Title: '1. Body Metrics',
    step2Title: '2. Goals & Level',
    step3Title: '3. Equipment & Safety',
    ageLabel: 'Age',
    genderLabel: 'Gender',
    male: 'Male',
    female: 'Female',
    heightLabel: 'Height (cm)',
    weightLabel: 'Weight (kg)',
    calculatedBmi: 'Calculated BMI',
    goalTitle: 'Primary Fitness Goal',
    goalMuscleGain: '💪 Build Muscle & Strength',
    goalWeightLoss: '🔥 Fat Loss & Toning',
    goalEndurance: '⚡ Endurance & Stamina',
    goalRecovery: '🧘 Mobility & Recovery',
    experienceTitle: 'Experience Level',
    beginner: 'Beginner (0 - 6 mos)',
    intermediate: 'Intermediate (6m - 2 yrs)',
    advanced: 'Advanced (2+ yrs)',
    equipmentTitle: 'Available Equipment',
    equipBodyweight: '🏠 Bodyweight (No Gear)',
    equipDumbbell: '🏋️ Dumbbells at Home',
    equipFullGym: '🏢 Full Gym Access',
    equipBands: '🔗 Resistance Bands',
    injuryTitle: 'Areas to Protect / Avoid',
    injuryNone: '✅ None (Healthy)',
    injuryKnee: '🦵 Knee Sensitivity',
    injuryBack: '🦴 Lower Back Caution',
    injuryShoulder: '🦾 Shoulder Caution',
    nextStep: 'Next Step ➔',
    prevStep: 'Back',
    finishOnboarding: '✓ Complete & Create AI Plan',
    editProfile: 'Edit Fitness Profile',
    dailyWorkoutTitle: "Today's AI Adaptive Workout",
    dailyWorkoutSubtitle: "Personalized for your goal & equipment",
    readinessScoreLabel: 'Readiness Score',
    fitnessScoreLabel: 'Fitness Score™',
    customSearchTitle: 'Explore & Custom AI Search',
  },
  vi: {
    browse: 'Tra cứu',
    browseTitle: 'Thư viện bài tập',
    searchByName: 'Tìm theo tên (tiếng Anh hoặc tiếng Việt)',
    all: 'Tất cả',
    noResultsFound: 'Không tìm thấy bài tập nào.',
    loadingMore: 'Đang tải thêm...',
    appTitle: 'Gợi Ý AI Thể Hình',
    profile: 'Hồ sơ',
    inputPlaceholder: 'Mô tả bài tập bạn muốn (ví dụ: tập xô với tạ đơn tại nhà)',
    getSuggestions: 'Phân Tích & Gợi Ý AI',
    loading: 'AI đang phân tích...',
    recommendedFor: 'Nhóm cơ trọng tâm',
    noExercisesFound: 'Không tìm thấy bài tập phù hợp.',
    enterLongerDescription: 'Vui lòng nhập ít nhất 3 ký tự',
    failedToConnect: 'Không kết nối được backend',
    instructions: 'Hướng dẫn thực hiện',
    secondaryMuscles: 'Nhóm cơ phụ tác động',
    noInstructions: 'Chưa có hướng dẫn cho bài tập này.',
    saveToFavorites: 'Lưu vào Yêu thích',
    saved: 'Đã lưu',
    saving: 'Đang lưu...',
    logWorkout: 'Ghi nhận tập luyện (RPE & Set)',
    sets: 'Số hiệp (Sets)',
    reps: 'Số lần (Reps)',
    weightKg: 'Mức tạ (kg)',
    rpeScore: 'Mức độ gắng sức RPE (1-10)',
    confirmLog: 'Xác nhận ghi nhận',
    workoutLogged: 'Đã ghi nhận buổi tập thành công!',
    success: 'Thành công',
    error: 'Lỗi',
    login: 'Đăng nhập',
    loggingIn: 'Đang đăng nhập...',
    signUp: 'Đăng ký',
    creatingAccount: 'Đang tạo tài khoản...',
    email: 'Email',
    password: 'Mật khẩu',
    passwordMin: 'Mật khẩu (tối thiểu 6 ký tự)',
    name: 'Tên',
    noAccount: 'Chưa có tài khoản? Đăng ký',
    haveAccount: 'Đã có tài khoản? Đăng nhập',
    createAccount: 'Tạo tài khoản',
    passwordTooShort: 'Mật khẩu phải có ít nhất 6 ký tự',
    favoriteExercises: '⭐ Bài tập yêu thích',
    workoutHistory: '📋 Lịch sử tập luyện',
    logOut: 'Đăng xuất',
    noFavorites: 'Chưa có bài tập yêu thích nào.',
    remove: 'Xóa',
    noWorkoutLogs: 'Chưa có lịch sử tập luyện nào.',
    language: 'Ngôn ngữ',
    detail: 'Chi Tiết Bài Tập',
    favoritesTitle: 'Yêu Thích',
    historyTitle: 'Lịch Sử Tập',
    profileTitle: 'Hồ Sơ',
    adminDashboard: 'Thống kê hệ thống',
    adminExercises: 'Quản lý bài tập',
    totalUsers: 'Tổng người dùng',
    totalExercises: 'Tổng bài tập',
    totalFavorites: 'Tổng lượt yêu thích',
    totalWorkoutLogs: 'Tổng nhật ký tập',
    mostFavorited: 'Bài tập được yêu thích nhất',
    addExercise: 'Thêm bài tập',
    editExercise: 'Sửa bài tập',
    deleteExercise: 'Xóa',
    confirmDelete: 'Bạn có chắc muốn xóa bài tập này?',
    save: 'Lưu',
    cancel: 'Hủy',
    bodyPart: 'Nhóm cơ',
    equipment: 'Dụng cụ',
    exerciseName: 'Tên bài tập',
    // AI Accuracy & SRS Keys
    aiAccuracy: 'Độ chính xác AI ~95%',
    aiEngineBadge: 'Động cơ AI Thích nghi Sẵn sàng',
    aiConfidence: 'Độ Tin Cậy AI',
    confidenceHigh: 'Độ chính xác cao',
    confidenceMedium: 'Độ chính xác trung bình',
    confidenceLow: 'Độ tin cậy thấp',
    identifiedKeywords: 'Từ khóa AI nhận diện',
    alternativeSuggestions: 'Chuyển nhanh nhóm cơ liên quan',
    clarificationTip: 'Mẹo: Bạn có thể thêm dụng cụ hoặc tên nhóm cơ cụ thể để AI gợi ý chuẩn xác hơn.',
    quickPrompts: 'Chọn nhanh mục tiêu tập',
    match: 'Phù hợp',
    formGuidance: 'Hướng Dẫn Form Chuẩn AI (Computer Vision)',
    formAccuracyTarget: 'Tiêu chuẩn Form AI ≥ 85%',
    formTipChest: 'Khóa bả vai về sau, giữ lưng thẳng tự nhiên và kiểm soát lực ngực khi đẩy.',
    formTipBack: 'Kéo bằng khuỷu tay, siết cơ xô ở điểm cuối và hạn chế đung đưa thân người.',
    formTipLegs: 'Đầu gối hướng theo mũi chân, giữ ngực mở và cột sống thẳng khi xuống tấn.',
    formTipShoulders: 'Không mở cùi chỏ quá rộng ra sau và hạ tạ có kiểm soát.',
    formTipDefault: 'Duy trì nhịp thở đều đặn, đi hết biên độ chuyển động (full ROM) và kiểm soát nhịp độ.',
    substitutionsTitle: 'Bài Tập Thay Thế (Cùng Nhóm Cơ)',
    noSubstitutions: 'Chưa có bài tập thay thế phù hợp.',
    // Onboarding & Profile Keys (FR-002, FR-004, FR-005 SRS)
    onboardingTitle: 'Thiết Lập Hồ Sơ Thể Lực',
    onboardingSubtitle: 'Để AI cá nhân hóa lộ trình tập luyện tối ưu nhất cho cơ thể bạn.',
    step1Title: '1. Chỉ Số Cơ Thể',
    step2Title: '2. Mục Tiêu & Trình Độ',
    step3Title: '3. Dụng Cụ & An Toàn',
    ageLabel: 'Tuổi',
    genderLabel: 'Giới tính',
    male: 'Nam',
    female: 'Nữ',
    heightLabel: 'Chiều cao (cm)',
    weightLabel: 'Cân nặng (kg)',
    calculatedBmi: 'Chỉ số BMI ước tính',
    goalTitle: 'Mục tiêu tập luyện chính',
    goalMuscleGain: '💪 Tăng Cơ & Sức Mạnh',
    goalWeightLoss: '🔥 Giảm Mỡ & Săn Chắc',
    goalEndurance: '⚡ Sức Bền & Tim Mạch',
    goalRecovery: '🧘 Phục Hồi & Dẻo Dai',
    experienceTitle: 'Trình độ tập luyện',
    beginner: 'Người mới (0 - 6 tháng)',
    intermediate: 'Trung cấp (6 tháng - 2 năm)',
    advanced: 'Nâng cao (Trên 2 năm)',
    equipmentTitle: 'Dụng cụ bạn có thể dùng',
    equipBodyweight: '🏠 Không tạ (Tại nhà)',
    equipDumbbell: '🏋️ Tạ đơn tại nhà',
    equipFullGym: '🏢 Phòng Gym đầy đủ',
    equipBands: '🔗 Dây kháng lực',
    injuryTitle: 'Vùng cần lưu ý / Tránh chấn thương',
    injuryNone: '✅ Không có (Khỏe mạnh)',
    injuryKnee: '🦵 Khớp gối nhạy cảm',
    injuryBack: '🦴 Cột sống / Lưng dưới',
    injuryShoulder: '🦾 Khớp vai',
    nextStep: 'Tiếp tục ➔',
    prevStep: 'Quay lại',
    finishOnboarding: '✓ Hoàn Tất & Tạo Lộ Trình AI',
    editProfile: 'Chỉnh Sửa Hồ Sơ Thể Lực',
    dailyWorkoutTitle: "Buổi Tập Thích Nghi Hôm Nay",
    dailyWorkoutSubtitle: "Được AI tối ưu theo mục tiêu & dụng cụ của bạn",
    readinessScoreLabel: 'Chỉ số sẵn sàng',
    fitnessScoreLabel: 'Điểm Thể Lực™',
    customSearchTitle: 'Khám Phá & Tìm Kiếm Tự Do',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    const loadLang = async () => {
      const stored = await AsyncStorage.getItem('app_language');
      if (stored === 'en' || stored === 'vi') setLang(stored);
      setLoaded(true);
    };
    loadLang();
  }, []);

  const changeLanguage = async (newLang) => {
    setLang(newLang);
    await AsyncStorage.setItem('app_language', newLang);
  };

  const t = (key) => translations[lang]?.[key] ?? key;

  if (!loaded) return null;

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
